name=ESP32-OBD
version=1.0.0
author=EastMarketSideProjects
sentence=An asynchronus library to handle OBD communication on ESP32.
url=https://github.com/EastMarketSideProjects/esp32-obd2
architectures=*